# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  appName: 'angular-tour-of-heroes'

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'environment.ts'
  displayName: "Download environment.ts"

- task: CopyFiles@2
  inputs:
    sourceFolder: "$(Agent.TempDirectory)"
    contents: "environment.ts"
    targetFolder: "$(System.DefaultWorkingDirectory)/client/src/environments"
  displayName: "Import environment.ts"

- script: |
    npm install -g @angular/cli
    npm ci
  workingDirectory: '$(System.DefaultWorkingDirectory)/client'
  displayName: 'npm install'

- script: |
    npm install -g @angular/cli
    ng build
  workingDirectory: '$(System.DefaultWorkingDirectory)/client'
  displayName: 'build'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(System.ArtifactStagingDirectory)/dist'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/client/dist/$(appName)'
    TargetFolder: '$(System.ArtifactStagingDirectory)/dist'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(827db528-0c2a-498e-ab18-90f98ae67a68)'
    appType: 'webAppLinux'
    WebAppName: 'angularssrheroes'
    packageForLinux: '$(System.ArtifactStagingDirectory)/dist/server'
    RuntimeStack: 'NODE|20-lts'
    StartupCommand: 'pm2 server.mjs'
  displayName: 'Deploy ssr web app'